name: myenv
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.4.2
  - pytorch=2.2.1
  - pytorch-cuda=12.1  # Add explicit CUDA dependency
  - cudatoolkit  # Add CUDA toolkit
  - tqdm
  - pip
  - pip:
      - torch-geometric==2.3.1